export const SIGNUP_REQUEST ='SIGNUP_REQUEST'
export const SIGNUP_SUCCESS ='SIGNUP_SUCCESS'
export const SIGNUP_FAIL ='SIGNUP_FAIL'

export const SIGNUP_VERIFY_REQUEST ='SIGNUP_VERIFY_REQUEST'
export const SIGNUP_VERIFY_SUCCESS ='SIGNUP_VERIFY_SUCCESS'
export const SIGNUP_VERIFY_FAIL ='SIGNUP_VERIFY_FAIL'

export const CLEAR_ERRORS ='CLEAR_ERRORS'