const JoinUsData = [
    {
        id: 81561,
        Job_name: 'HRBP',
        position:"People Operation",
        address:'Saravanampatti - Coimbatore | HSR Layout',
        location:'Bengaluru, India +1',
        experience:'1-10 Year',
        description:"Kalvium is reimagining the higher education sector from the ground up by challenging existing assumptions and making degree programs more relevant and engaging. We are funded and backed by top technology leaders and CTOs from global organizations and unicorns like Google, Microsoft, Flipkart, Ola, CRED, Zerodha, and PhonePe. We are looking for a Campus Program Manager who shares our passion for making a difference in the field of engineering education and enjoys working with multiple stakeholders in a dynamic environment.",
        eligibility:' A Kalvium Talent Acquisition Specialist serves as the glue that ties the program deliverables and the business growth together and acts as a role model for our future Software Engineers. Before applying, review the following requisites that we expect from a TAG Specialist at Kalvium:',
        education:'Any PostGraduate',
        Skills: 'Campus , Learning, Managament ,program Management , Data Communication',
        industry: 'Education / Teaching / Training',
        experiencelevel:'Entry Level',
        salary:'INR 600,000 - 700,000',
        employmenttype:'Full-Time',
        workplacetype:'In-Office',
        benefit:'● Opportunity to be part of an impactful movement to transform higher education for ● the better, with a competitive salary. ● This challenging role is designed to significantly enhance your professional profile and skills. ● Work closely with the founders and the founding team. ● Enjoy an awesome work culture that helps you thrive with the team.',
        eligibilitypoint1:'  Knowledge of edtech and sales industry tendencies, the competitive environment, and best practices.',
        eligibilitypoint2:'   Solid comprehension of HR policies and practices.Capability to assess candidates’ suitability for a position.',
    },
    {
        id: 80684,
        Job_name: 'Program Manager (Campus)',
        position:"Program Delivery",
        location:'Jaipur, India + 2 ',
        experience:'0-2 Year',
        description:"Basic Eligibility: A Kalvium Talent Acquisition Specialist serves as the glue that ties the program deliverables and the business growth together and acts as a role model for our future Software Engineers. Before applying, review the following requisites that we expect from a TAG Specialist at Kalvium: ·      Develops, facilitates, and implements all phases of the recruitment process.·      Collaborates with stakeholders to identify and draft detailed and accurate job descriptions and hiring criteria. ·      Screens applications and selects qualified candidates·      Schedule interviews; oversee preparation of interview questions and other hiring and selection materials.",
        eligibility:'A Kalvium Campus Program Manager serves as the glue that ties the program together and acts as a role model for our future Software Engineers. Before applying, consider the following questions:● Are you interested in helping students succeed in their careers?● Do you enjoy mentoring students?● Do you possess good communication and presentation skills?● Are you a good listener?● Are you proficient in working with data?● Are you considering Program Management as a future career option?',
        education:'Any PostGraduate',
        Skills: 'Campus , Learning, Managament ,program Management , Data Communication',
        industry: 'Education / Teaching / Training',
        experiencelevel:'Entry Level',
        salary:'INR 500,000 - 700,000',
        employmenttype:'Part-Time',
        address:'Saravanampatti - Coimbatore | HSR Layout',
        workplacetype:'In-Office',
        benefit:'● Opportunity to be part of an impactful movement to transform higher education for ● the better, with a competitive salary. ● This challenging role is designed to significantly enhance your professional profile and skills. ● Work closely with the founders and the founding team. ● Enjoy an awesome work culture that helps you thrive with the team.',
        eligibilitypoint1:'  Knowledge of edtech and sales industry tendencies, the competitive environment, and best practices.',
        eligibilitypoint2:'   Solid comprehension of HR policies and practices.Capability to assess candidates’ suitability for a position.',
    },
    {
        id: 80674,
        Job_name: 'Performance Marketer',
        position:"Digital Markeitng",
        location:'Bengaluru, India +1',
        experience:'1-8 Year',
        description:"Basic Eligibility: A Kalvium Talent Acquisition Specialist serves as the glue that ties the program deliverables and the business growth together and acts as a role model for our future Software Engineers. Before applying, review the following requisites that we expect from a TAG Specialist at Kalvium: ·      Develops, facilitates, and implements all phases of the recruitment process.·      Collaborates with stakeholders to identify and draft detailed and accurate job descriptions and hiring criteria. ·      Screens applications and selects qualified candidates·      Schedule interviews; oversee preparation of interview questions and other hiring and selection materials.",
        eligibility:'A Kalvium Campus Program Manager serves as the glue that ties the program together and acts as a role model for our future Software Engineers. Before applying, consider the following questions:● Are you interested in helping students succeed in their careers?● Do you enjoy mentoring students?● Do you possess good communication and presentation skills?● Are you a good listener?● Are you proficient in working with data?● Are you considering Program Management as a future career option?',
        education:'Any PostGraduate',
        Skills: 'Campus , Learning, Managament ,program Management , Data Communication',
        industry: 'Education / Teaching / Training',
        experiencelevel:'Entry Level',
        salary:'INR 200,000 - 700,000',
        employmenttype:'Part-Time',
        address:'Saravanampatti - Coimbatore | HSR Layout',
        workplacetype:'In-Office',
        benefit:'● Opportunity to be part of an impactful movement to transform higher education for ● the better, with a competitive salary. ● This challenging role is designed to significantly enhance your professional profile and skills. ● Work closely with the founders and the founding team. ● Enjoy an awesome work culture that helps you thrive with the team.',
        eligibilitypoint1:'  Knowledge of edtech and sales industry tendencies, the competitive environment, and best practices.',
        eligibilitypoint2:'   Solid comprehension of HR policies and practices.Capability to assess candidates’ suitability for a position.',
    },
    {
        id: 80634,
        Job_name: 'Senior Data Scientist / Engineer',
        position:"Product Engineering",
        location:'Bengaluru, India +1',
        experience:'6-10 Year',
        description:"Basic Eligibility: A Kalvium Talent Acquisition Specialist serves as the glue that ties the program deliverables and the business growth together and acts as a role model for our future Software Engineers. Before applying, review the following requisites that we expect from a TAG Specialist at Kalvium: ·      Develops, facilitates, and implements all phases of the recruitment process.·      Collaborates with stakeholders to identify and draft detailed and accurate job descriptions and hiring criteria. ·      Screens applications and selects qualified candidates·      Schedule interviews; oversee preparation of interview questions and other hiring and selection materials.",
        eligibility:'A Kalvium Campus Program Manager serves as the glue that ties the program together and acts as a role model for our future Software Engineers. Before applying, consider the following questions:● Are you interested in helping students succeed in their careers?● Do you enjoy mentoring students?● Do you possess good communication and presentation skills?● Are you a good listener?● Are you proficient in working with data?● Are you considering Program Management as a future career option?',
        education:'Any PostGraduate',
        Skills: 'Campus , Learning, Managament ,program Management , Data Communication',
        industry: 'Education / Teaching / Training',
        experiencelevel:'Entry Level',
        salary:'INR 200,000 - 700,000',
        employmenttype:'Part-Time',
        address:'Saravanampatti - Coimbatore | HSR Layout',
        workplacetype:'In-Office',
        benefit:'● Opportunity to be part of an impactful movement to transform higher education for ● the better, with a competitive salary. ● This challenging role is designed to significantly enhance your professional profile and skills. ● Work closely with the founders and the founding team. ● Enjoy an awesome work culture that helps you thrive with the team.',
        eligibilitypoint1:'  Knowledge of edtech and sales industry tendencies, the competitive environment, and best practices.',
        eligibilitypoint2:'   Solid comprehension of HR policies and practices.Capability to assess candidates’ suitability for a position.',
    },
    {
        id: 80644,
        Job_name: 'Senior/ Lead - Full Stack Developer',
        position:"Product",
        location:'Bengaluru, India +1',
        experience:'6-15 Year',
        description:"Basic Eligibility: A Kalvium Talent Acquisition Specialist serves as the glue that ties the program deliverables and the business growth together and acts as a role model for our future Software Engineers. Before applying, review the following requisites that we expect from a TAG Specialist at Kalvium: ·      Develops, facilitates, and implements all phases of the recruitment process.·      Collaborates with stakeholders to identify and draft detailed and accurate job descriptions and hiring criteria. ·      Screens applications and selects qualified candidates·      Schedule interviews; oversee preparation of interview questions and other hiring and selection materials.",
        eligibility:'A Kalvium Campus Program Manager serves as the glue that ties the program together and acts as a role model for our future Software Engineers. Before applying, consider the following questions:● Are you interested in helping students succeed in their careers?● Do you enjoy mentoring students?● Do you possess good communication and presentation skills?● Are you a good listener?● Are you proficient in working with data?● Are you considering Program Management as a future career option?',
        education:'Any PostGraduate',
        Skills: 'Campus , Learning, Managament ,program Management , Data Communication',
        industry: 'Education / Teaching / Training',
        experiencelevel:'Entry Level',
        salary:'INR 200,000 - 700,000',
        employmenttype:'Part-Time',
        address:'Saravanampatti - Coimbatore | HSR Layout',
        workplacetype:'In-Office / Work From Office',
        benefit:'● Opportunity to be part of an impactful movement to transform higher education for ● the better, with a competitive salary. ● This challenging role is designed to significantly enhance your professional profile and skills. ● Work closely with the founders and the founding team. ● Enjoy an awesome work culture that helps you thrive with the team.',
        eligibilitypoint1:'  Knowledge of edtech and sales industry tendencies, the competitive environment, and best practices.',
        eligibilitypoint2:'   Solid comprehension of HR policies and practices.Capability to assess candidates’ suitability for a position.',
    },
]

export default JoinUsData